### ISSUE TITLE
Split tunneling not working for RuneLite - Java application

### ISSUE THREAD

**Issue by mytee12** [mullvad/mullvadvpn-app#2972]
## Issue report

Operating system: Windows 10 x64

App version: 2021.4

### Issue description

Split tunneling on Mullvad does not work for game client RuneLite with the error "RuneLite encountered a fatal error while downloading the bootstrap" on startup of the application. I believe this is a Java application.

RuneLite works with no VPN and works with it being tunneled through the VPN. Stops working as you add the process to be split tunneled. 

Download for [Runelite ](https://runelite.net/)can be found at : https://github.com/runelite/launcher/releases/download/2.1.7/RuneLiteSetup.exe . You do not need an account or setup to test this. After installation (default options) The process can be found at %localappdata%/runelite/Runelite.exe

Logs of Runelite:
``
2021-09-18 22:42:35 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.1.7
2021-09-18 22:42:35 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2021-09-18 22:42:35 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.net.SocketException: Permission denied: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:399)
	at net.runelite.launcher.Launcher.main(Launcher.java:241)
``

**Comment by RedCard1nal** [comment]
I am also having this same problem. I just got back into RS for the first time since switching Mullvad was going to make a post of my own.

**Comment by mvd-ows** [comment]
Thanks for reporting this issue. We'll look into it and get back to you.

**Comment by mvd-ows** [comment]
Turns out it's an issue with the specific Java runtime used by this game. It's pretending to make IPv6 connections but using IPv4 peer addresses encoded as IPv6 addresses.

I've experimented with updating the driver code to see if this case can be handled, alas rewriting these connections causes them to break. It doesn't seem to be something we can address using the current approach to splitting.

The 2021.4 release will break or drop these connections depending on a few different factors. There are no traffic leaks.

**Comment by robmonte** [comment]
I see this is marked as wontfix and is 2 years old, but this issue still persists with the application today. The author of Runelite has looked into the problem on the application side and seems to believe that the issue is on Mullvad's side.

[IPv4-mapped IPv6 address](https://datatracker.ietf.org/doc/html/rfc4291#section-2.5.5.2) is a valid format for compatibility, so I am wondering if anything has changed in the last two years that might make supporting this feature possible?

**Comment by bob7l** [comment]
> Turns out it's an issue with the specific Java runtime used by this game. It's pretending to make IPv6 connections but using IPv4 peer addresses encoded as IPv6 addresses.
> 
> I've experimented with updating the driver code to see if this case can be handled, alas rewriting these connections causes them to break. It doesn't seem to be something we can address using the current approach to splitting.
> 
> The 2021.4 release will break or drop these connections depending on a few different factors. There are no traffic leaks.

Couldn't you just check if a ipv6 is IPv4-mapped in the driver, then convert it to a ipv4? Check in the register_ips function, etc..
