### ISSUE TITLE
AttributeError during startup on Ubuntu 18.04

### ISSUE THREAD

**Issue by bjoluc** [mullvad/mullvadvpn-app#308]
When running `env MULLVAD_USE_GTK3=yes mullvad` on Ubuntu 18.04 it fails with the following output:

```
Using GTK3
/usr/lib/python2.7/dist-packages/mullvad/mui.py:60: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
changing directory to /usr/lib/python2.7/dist-packages/mullvad
Setting logging directory to /home/username/.cache/mullvad/log

(mullvad:4885): Gtk-WARNING **: 10:01:38.719: gtk_disable_setlocale() must be called before gtk_init()
Setting logging directory to /home/username/.cache/mullvad/log
CRITICAL: An uncaught exception occured: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 16765, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python2.7/dist-packages/mullvad/mui.py", line 2088, in _start
    _start_gui(app, root_window, log, settings, tunnel)
  File "/usr/lib/python2.7/dist-packages/mullvad/mui.py", line 2138, in _start_gui
    tray_ui = AppIndicator(root_window, tunnel, settings)
  File "/usr/lib/python2.7/dist-packages/mullvad/mui.py", line 295, in __init__
    appindicator.CATEGORY_COMMUNICATIONS)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.AppIndicator3' object has no attribute 'CATEGORY_COMMUNICATIONS'
```

Adding `gi.require_version('AppIndicator3', '0.1')` in line 60 of `mui.py` has no effect on the `AttributeError`.
I have `mullvad_67-1_all.deb` installed.
Any fix would be greatly appreciated!

**Comment by faern** [comment]
Hi @bjoluc The program you are trying to run and the code you are talking about is pertaining to our older Python based client. This repository is for a completely different VPN client that we are developing. This new VPN client app will very soon have Linux support and will then supersede the one you are trying to run.

For help with the python client please contact support directly at support@mullvad.net

**Comment by faern** [comment]
Closing since issue is related to a different code base and program.
