### ISSUE TITLE
string.prototype.trimend not accessible from es-abstract

### ISSUE THREAD

**Issue by IanQS** [mullvad/mullvadvpn-app#3222]
Manjaro Linux Kernel `5.13.19-2` 

App version: - 

Downloading the official package from the [mullvad-vpn 2021.6-2
](https://aur.archlinux.org/packages/mullvad-vpn/?O=0&PP=10) and going through the usual installation instructions (building from source, and using `pamac`) leads to the error of 

```
/var/tmp/pamac-build-iq/mullvad-vpn/src/mullvadvpn-app/gui /var/tmp/pamac-build-iq/mullvad-vpn/src/mullvadvpn-app
Installing JavaScript dependencies...
npm ERR! string.prototype.trimend not accessible from es-abstract

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/tmp/pamac-build-iq/mullvad-vpn/src/npm-cache/_logs/2021-12-28T07_34_10_661Z-debug.log
==> ERROR: A failure occurred in build().
```

The contents of `/var/tmp/pamac-build-iq/mullvad-vpn/src/npm-cache/_logs/2021-12-28T07_34_10_661Z-debug.log` show 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/iq/emsdk/node/14.15.5_64bit/bin/node',
1 verbose cli   '/home/iq/emsdk/node/14.15.5_64bit/bin/npm',
1 verbose cli   'ci',
1 verbose cli   '--cache',
1 verbose cli   '/var/tmp/pamac-build-iq/mullvad-vpn/src/npm-cache'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose npm-session b2bd3e045e2464e4
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /var/tmp/pamac-build-iq/mullvad-vpn/src/mullvadvpn-app/gui
8 verbose prepare using package-lock.json
9 verbose checkLock verifying package-lock data
10 verbose teardown shutting down workers.
11 info teardown Done in 0s
12 verbose stack Error: string.prototype.trimend not accessible from es-abstract
12 verbose stack     at reqAddr (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:159:17)
12 verbose stack     at /home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:129:22
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at addChild (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
12 verbose stack     at /home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at addChild (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
12 verbose stack     at /home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at addChild (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
12 verbose stack     at /home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:133:7
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at addChild (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:128:40)
12 verbose stack     at /home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:113:5
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at lockTree (/home/iq/emsdk/node/14.15.5_64bit/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:107:5)
13 verbose cwd /var/tmp/pamac-build-iq/mullvad-vpn/src/mullvadvpn-app/gui
14 verbose Linux 5.13.19-2-MANJARO
15 verbose argv "/home/iq/emsdk/node/14.15.5_64bit/bin/node" "/home/iq/emsdk/node/14.15.5_64bit/bin/npm" "ci" "--cache" "/var/tmp/pamac-build-iq/mullvad-vpn/src/npm-cache"
16 verbose node v14.15.5
17 verbose npm  v6.14.11
18 error string.prototype.trimend not accessible from es-abstract
19 verbose exit [ 1, true ]
```

Do let me know if there is anything else I can provide. I've been looking around but I have no idea what packages were installed to make `mullvad` usable. Looking online to find solutions I found a [few solutions](https://www.google.com/search?q=string.prototype.trimend+not+accessible+from+es-abstract&oq=string.prototype.trimend+not+accessible+from+es-abstract&aqs=chrome.0.69i59j0i22i30l2j69i60l2.371j0j7&sourceid=chrome&ie=UTF-8) I have no idea what line to edit as I'm not familiar with node.

**Comment by raksooo** [comment]
This is caused by using NPM 6.x. Try using the latest release of Node 16 and the latest release of NPM. More information and instructions can be found here: https://github.com/mullvad/mullvadvpn-app#all-platforms

**Comment by IanQS** [comment]
Gotcha! Thank you :) I assumed the issue was in the build process and not that my versions were out of date; I had previously installed it and everything seemed to work fine OOTB.

closing
