### ISSUE TITLE
mullvad u expectedly crashes on android 12L

### ISSUE THREAD

**Issue by SalarIonck** [mullvad/mullvadvpn-app#3639]
The operating system version is Android 12L, and the app version is 2022.1
Every time I open Mullvad VPN, I can use it briefly before it crashes unexpectedly, Here is the crash log if it can help you.
`FATAL EXCEPTION: main
Process: net.mullvad.mullvadvpn, PID: 22351
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	... 1 more
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.os.IMessenger$Stub$Proxy.send(IMessenger.java:125)
	at android.os.Messenger.send(Messenger.java:59)
	at net.mullvad.mullvadvpn.ui.serviceconnection.ConnectionProxy.connect(ConnectionProxy.kt:37)
	at net.mullvad.mullvadvpn.ui.ConnectFragment$onSafelyCreateView$$inlined$apply$lambda$1.invoke(ConnectFragment.kt:68)
	at net.mullvad.mullvadvpn.ui.ConnectFragment$onSafelyCreateView$$inlined$apply$lambda$1.invoke(ConnectFragment.kt:23)
	at net.mullvad.mullvadvpn.ui.ConnectActionButton.action(ConnectActionButton.kt:86)
	at net.mullvad.mullvadvpn.ui.ConnectActionButton.access$action(ConnectActionButton.kt:11)
	at net.mullvad.mullvadvpn.ui.ConnectActionButton$1.onClick(ConnectActionButton.kt:67)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	... 3 more`

**Comment by albin-mullvad** [comment]
Thanks for reporting this issue! Which device is this happening on? It would be really helpful if you can submit a problem report from inside the app, with a description referring to this issue, e.g. "github issue 3639".

**Comment by SalarIonck** [comment]
Thank you for your reply. My device is an Xiaomi Redmi note 9s witch is running android 12L.
I had already filed a report detailing the problem, and I had received an email in which they requested the crash log, which I provided, and in which they informed me that the crash log  had been passed to the developers.

**Comment by albin-mullvad** [comment]
Sorry for the late reply! Thanks for sharing the report. We're investigating this issue that seem to be present on a few models, mostly Xiaomi, running recent Android versions.

**Comment by SalarIonck** [comment]
It's all right. I understand how difficult it can be to explore and resolve a problem. Take as much time as you and your team needs. 👍

**Comment by Rawa** [comment]
I don't believe this is an issue anymore, we've rewritten this ensure screen, so hopefully this is not a problem any more, please feel free to comment if you think this issue still is relevant.
