### ISSUE TITLE
[Windows 10] GUI fails to start - Mullvad 2019.1

### ISSUE THREAD

**Issue by NetroScript** [mullvad/mullvadvpn-app#749]
When downloading the latest version either on Github or on the official website and installing it, it installs without a problem, the tray icon appears, but no GUI is visible.
Looking at the process list the daemon is running fine + 2 other Mullvad processes. I tried out the command line version and it also worked fine together with the daemon, leaving a fault in the electron app. Running it in the command line revealed the following error: 

```
C:\Program Files\Mullvad VPN>
[2019-03-17 14:13:14.974][info] Running version 2019.1.0
[2019-03-17 14:13:14.976][error] Failed to read GUI settings file: Error: ENOENT: no such file or directory, open 'C:\Users\Jack\AppData\Local\Mullvad VPN\gui_settings.json'
[2019-03-17 14:13:14.976][info] Connecting to transport with params { path: '//./pipe/Mullvad VPN' }
[2019-03-17 14:13:14.979][debug] Connect socket
[2019-03-17 14:13:15.010][debug] Socket is ready
[2019-03-17 14:13:15.010][info] Transport is connected
(node:12604) UnhandledPromiseRejectionWarning: Error: Cannot find module 'electron-devtools-installer'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Program Files\Mullvad VPN\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object._installDevTools (C:\Program Files\Mullvad VPN\resources\app.asar\build\main\index.js:834:23)
    at Object._onReady (C:\Program Files\Mullvad VPN\resources\app.asar\build\main\index.js:295:18)
    at App._electron.app.on (C:\Program Files\Mullvad VPN\resources\app.asar\build\main\index.js:117:42)
    at App.emit (events.js:187:15)
(node:12604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-17 14:13:15.095][debug] Start relays periodic updates
```

(no new log lines after some minutes, also no GUI)

I manually fixed my local installation, by unpacking the app.asar from electron and adding `electron-devtools-installer` (additionally I also run a `npm install` to be safe). After repacking the app.asar, killing the current Mullvad processes and running the application again, the GUI appeared.
But following unwanted behavior appeared:
The Chromium Developer Tools now start up on every application start.

Now the logs is the following:
```
[2019-03-17 14:18:41.039][info] Running version 2019.1.0
[2019-03-17 14:18:41.041][error] Failed to read GUI settings file: Error: ENOENT: no such file or directory, open 'C:\Users\Jack\AppData\Local\Mullvad VPN\gui_settings.json'
[2019-03-17 14:18:41.041][info] Connecting to transport with params { path: '//./pipe/Mullvad VPN' }
[2019-03-17 14:18:41.044][debug] Connect socket
[2019-03-17 14:18:41.075][debug] Socket is ready
[2019-03-17 14:18:41.075][info] Transport is connected
[2019-03-17 14:18:41.191][debug] Start relays periodic updates
[2019-03-17 14:18:41.743][info] Error installing REACT_DEVELOPER_TOOLS extension: spawn C:\Program Files\Mullvad VPN\resources\app.asar\node_modules\7zip\7zip-lite\7z.exe ENOENT
[2019-03-17 14:18:41.951][info] Error installing REDUX_DEVTOOLS extension: spawn C:\Program Files\Mullvad VPN\resources\app.asar\node_modules\7zip\7zip-lite\7z.exe ENOENT
[2019-03-17 14:18:42.648][debug] Tunnel state: disconnected
```

Edit:
I just tried an entirely different computer at a different location, setup worked there without a problem.
Which seems strange for me, because I retried the installation multiple times (also after a restart) and both systems are very similar. (Considering running processes / installation of stuff like NodeJS/Electron/Compilers/Libraries/...)

**Comment by pronebird** [comment]
Hi,

I looks like you're attempting to run a production app using the `NODE_ENV` environment variable set to `development`. You shouldn't do this because we do not ship development dependencies with production apps. In the future, we will likely strip out all of the checks for `NODE_ENV` in production builds.

**Comment by NetroScript** [comment]
Ah yes, that is probably the problem, thanks for the clarification. I can confirm that the environment variable is set on one PC, but not on the other, so you can probably close this now. (Or you leave it open until you stripped it?)

**Comment by pronebird** [comment]
@NetroScript Thanks for reporting this!

Closing since I've submitted this issue to our internal bug tracking system.
